name: Build All Platforms

on:
  push:
    branches-ignore: [ master ]

jobs:

  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout commit code
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Install Package Manager Deps
      run: ./scripts/installLinuxDependencies.sh
    - name: Grab or Build Vcpkg Deps
      uses: lukka/run-vcpkg@v2
      with:
        vcpkgArguments: '@${{ github.workspace }}/vcpkg-deps.txt'
        vcpkgDirectory: '${{ github.workspace }}/vcpkg'
        appendedCacheKey: ${{ hashFiles('vcpkg-deps.txt') }}
    - name: Build executable
      run: ./linux-build.sh
    - name: Upload executable as artifact
      uses: actions/upload-artifact@v2
      with:
        name: linux-executable
        path: bin/forbidden-desert

  build-macos:
    runs-on: macos-latest

    steps:
    - name: Checkout commit code
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Grab or Build Vcpkg Deps
      uses: lukka/run-vcpkg@v2
      with:
        vcpkgArguments: '@${{ github.workspace }}/vcpkg-deps.txt'
        vcpkgDirectory: '${{ github.workspace }}/vcpkg'
        appendedCacheKey: ${{ hashFiles('vcpkg-deps.txt') }}
    - name: Build executable
      run: ./mac-build.sh
    - name: Upload executable as artifact
      uses: actions/upload-artifact@v2
      with:
        name: macOS-executable
        path: bin/forbidden-desert

  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout commit code
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.0
    - name: Grab or Build Vcpkg Deps
      uses: lukka/run-vcpkg@v2
      with:
        vcpkgArguments: '@${{ github.workspace }}/vcpkg-deps.txt'
        vcpkgDirectory: '${{ github.workspace }}/vcpkg'
        appendedCacheKey: ${{ hashFiles('vcpkg-deps.txt') }}
    - name: Build executable
      run: ./win-build.bat
    - name: Upload executable as artifact
      uses: actions/upload-artifact@v2
      with:
        name: windows-build
        path: bin/*
