name: Release

on:
  push:
    branches:
      - '**'

jobs:

  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout commit code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: ./ci/installLinuxDependencies.sh
    - name: Build executable
      run: ./linux-build.sh CI
    - name: Upload executable as artifact
      uses: actions/upload-artifact@v1
      with:
        name: linux-executable
        path: bin/forlorn-dryplace

  build-macos:
    runs-on: macos-latest

    steps:
    - name: Checkout commit code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: ./ci/installMacDependencies.sh
    - name: Build executable
      run: ./mac-build.sh
    - name: Upload executable as artifact
      uses: actions/upload-artifact@v1
      with:
        name: macOS-executable
        path: bin/forlorn-dryplace

  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout commit code
      uses: actions/checkout@v2
    - name: Install raylib
      run: ./ci/installWindowsDependencies
    - name: Build executable
      run: ./win-build.bat CI
    - name: Upload executable as artifact
      uses: actions/upload-artifact@v1
      with:
        name: windows-executable
        path: bin/forlorn-dryplace.exe