name: Build All Platforms

on:
  push:
    branches-ignore: [ master ]

jobs:

  build-server:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout commit code
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Install Package Manager Deps
      run: ./scripts/installLinuxDependencies.sh
    - name: Grab or Build Vcpkg Deps
      uses: lukka/run-vcpkg@v10.7
      with:
        vcpkgDirectory: '${{ github.workspace }}/vcpkg'
        vcpkgJsonGlob: '**/vcpkg.json'
        runVcpkgInstall: true
      env:
        VCPKG_INSTALLED_DIR: vcpkg_installed/
    - name: Build executable
      run: ./linux-build.sh
      working-directory: ./server
    - name: Archive the image
      run: docker save -o server-container-img.tar abalis3/forbidden-desert-server:local
    - name: Upload image as build artifact
      uses: actions/upload-artifact@v2
      with:
        name: server-container
        path: server-container-img.tar

  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout commit code
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Install Package Manager Deps
      run: ./scripts/installLinuxDependencies.sh
    - name: Grab or Build Vcpkg Deps
      uses: lukka/run-vcpkg@v10.7
      with:
        vcpkgDirectory: '${{ github.workspace }}/vcpkg'
        vcpkgJsonGlob: '**/vcpkg.json'
        runVcpkgInstall: true
      env:
        VCPKG_INSTALLED_DIR: vcpkg_installed/
    - name: List upper dir
      run: ls -la ..
      working-directory: ./client
    - name: List upper dir 3
      run: ls -la ../vcpkg
      working-directory: ./client
    - name: List upper dir 2
      run: ls -la ../vcpkg_installed
      working-directory: ./client
    - name: Build executable
      run: ./linux-build.sh
      working-directory: ./client
    - name: Upload executable as artifact
      uses: actions/upload-artifact@v2
      with:
        name: linux-executable
        path: client/bin/forbidden-desert

  build-macos-x86:
    runs-on: macos-13

    steps:
    - name: Checkout commit code
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Grab or Build Vcpkg Deps
      uses: lukka/run-vcpkg@v10.7
      with:
        vcpkgDirectory: '${{ github.workspace }}/vcpkg'
        vcpkgJsonGlob: '**/vcpkg.json'
        runVcpkgInstall: true
      env:
        VCPKG_INSTALLED_DIR: vcpkg_installed/
    - name: Build executable
      run: ./mac-build.sh
      working-directory: ./client
    - name: Upload executable as artifact
      uses: actions/upload-artifact@v2
      with:
        name: macOS-executable
        path: client/bin/forbidden-desert

  build-macos-arm:
    runs-on: macos-14

    steps:
    - name: Checkout commit code
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Grab or Build Vcpkg Deps
      uses: lukka/run-vcpkg@v10.7
      with:
        vcpkgDirectory: '${{ github.workspace }}/vcpkg'
        vcpkgJsonGlob: '**/vcpkg.json'
        runVcpkgInstall: true
      env:
        VCPKG_INSTALLED_DIR: vcpkg_installed/
        VCPKG_DEFAULT_TRIPLET: arm64-osx
    - name: Build executable
      run: ./mac-build.sh
      working-directory: ./client
    - name: Upload executable as artifact
      uses: actions/upload-artifact@v2
      with:
        name: macOS-executable
        path: client/bin/forbidden-desert

  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout commit code
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.3.1
    - name: Grab or Build Vcpkg Deps
      uses: lukka/run-vcpkg@v10.7
      with:
        vcpkgDirectory: '${{ github.workspace }}/vcpkg'
        vcpkgJsonGlob: '**/vcpkg.json'
        runVcpkgInstall: true
      env:
        VCPKG_INSTALLED_DIR: vcpkg_installed/
        VCPKG_DEFAULT_TRIPLET: x86-windows
    - name: Build executable
      run: ./win-build.bat
      working-directory: ./client
    - name: Upload executable as artifact
      uses: actions/upload-artifact@v2
      with:
        name: windows-build
        path: client/bin/*
