name: Build and Release

on:
  push:
    branches: [ master ]

jobs:

  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout commit code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: ./ci/installLinuxDependencies.sh
    - name: Build executable
      run: ./linux-build.sh CI
    - name: Upload executable as artifact
      uses: actions/upload-artifact@v1
      with:
        name: linux-executable
        path: bin/forbidden-desert

  build-macos:
    runs-on: macos-latest

    steps:
    - name: Checkout commit code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: ./ci/installMacDependencies.sh
    - name: Build executable
      run: ./mac-build.sh
    - name: Upload executable as artifact
      uses: actions/upload-artifact@v1
      with:
        name: macOS-executable
        path: bin/forbidden-desert

  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout commit code
      uses: actions/checkout@v2
    - name: Install raylib
      run: ./ci/installWindowsDependencies
    - name: Build executable
      run: ./win-build.bat CI
    - name: Upload executable as artifact
      uses: actions/upload-artifact@v1
      with:
        name: windows-executable
        path: bin/forbidden-desert.exe

  release:
    runs-on: ubuntu-latest
    needs:
      - build-linux
      - build-macos
      - build-windows

    steps:
    - name: Checkout commit code
      uses: actions/checkout@v2
    - name: Download linux build artifact
      uses: actions/download-artifact@v1
      with:
        name: linux-executable
    - name: Download mac build artifact
      uses: actions/download-artifact@v1
      with:
        name: macOS-executable
    - name: Download windows build artifact
      uses: actions/download-artifact@v1
      with:
        name: windows-executable
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Install semantic-release and plugins
      run: |
        npm install -g semantic-release@17
        npm install -g @semantic-release/exec@5
    - name: Release with semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
      run: npx semantic-release